// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ESPRESSO.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20231123013734_updateemail")]
    partial class updateemail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ESPRESSO.Models.UrlData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("COUNT")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LAST_UPDATED_DATE_AND_TIME")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("STREAM_NAME")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("emailId")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("pagecounter", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
